### ISSUE TITLE
About model weights & checkpoints

### ISSUE THREAD

**Issue by Louis-Leee** [NahyukLEE/pmtr#3]
Hi,

Thanks for your reply on the code release. The code works well! 
But the training phase needs more than 5 days with 150 epochs, so I just want to know whether you will release the checkpoints for testing?

**Comment by NahyukLEE** [comment]
Hi @Louis-Leee,

We have just uploaded our checkpoints (for both `everyday` and `artifact` subsets) on [Google Drive](https://drive.google.com/drive/folders/1N7uXu0xR1O9cpPnJTP7d6susR6hDj5nn?usp=sharing). Please check them out!

Best,
Nahyuk

**Comment by Louis-Leee** [comment]
Thanks! I will close the issue
